---
# If your project uses sonarqube (https://www.sonarsource.com/products/sonarqube/) configure it here
# the properties url, token, project, pull_request are most important to configure
sonarqube:
  # base-url for your sonarqube api. E.g. https://mysonar.example.com/
  url: "test"
  # How to create a token: https://docs.sonarsource.com/sonarqube/9.8/user-guide/user-account/generating-and-using-tokens/
  token: "_"
  # The Project key
  project: "_"
  # Pullrequest id
  pull_request: "1"

  # retrieve these metric types for the global metrics. An empty list will probably return all
  # https://docs.sonarsource.com/sonarqube/9.9/user-guide/metric-definitions/
  global_metric_types:
    - "new_coverage"
    - "new_sqale_debt_ratio"
    - "new_uncovered_conditions"
    - "new_violations"

github:
  # https://help.github.com/articles/creating-an-access-token-for-command-line-use/
  token: "token"
  # Name of your project. E.g. user/repo
  project: "test"
  # Pullrequest id
  pull_request: "1"

# you can ignore these
quarkus:
  native:
    additional-build-args: "--gc=epsilon"
