FROM quay.io/quarkus/quarkus-micro-image:2.0
COPY --chown=1001:root build/resources/main/application.yml /config/application.yml
COPY --chown=1001:root build/*-runner /qualityannotate

USER 1001

ENTRYPOINT ["/qualityannotate"]
