FROM alpine:3 as certs
RUN apk --update add ca-certificates

FROM scratch
WORKDIR /
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --chown=1001:root build/resources/main/application.yml /config/application.yml
COPY --chown=1001:root build/*-runner /qualityannotate

USER 1001

ENTRYPOINT ["/qualityannotate"]
