---
name: Build

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "master"
      - "main"
      - "develop"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --no-daemon
  build-native:
    name: "build-native"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build native
        run: ./gradlew build --no-daemon -Dquarkus.package.type=native
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: qualityannotate
          retention-days: 1
          path: ./build/qualityannotate-1.0.0-SNAPSHOT-runner
          if-no-files-found: error
  qualityannotate:
    needs: build-native
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download qualityannotate
        uses: actions/download-artifact@v3
        with:
          name: qualityannotate
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open
      - name: Qualityannotate
        uses: ./
        if: success() && steps.findPr.outputs.number
        with:
          pullRequest: ${{ steps.findPr.outputs.pr }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          githubProject: balrok/qualityannotate  # ${{env.GITHUB_ACTION_REPOSITORY}}
          sonarqubeProject: quyt_qualityannotate
          sonarqubeUrl: https://sonarcloud.io/
          sonarqubeToken: ${{ secrets.SONAR_TOKEN }}
