---
name: Build

on:  # yamllint disable-line rule:truthy
  - pull_request

jobs:
  qualityannotate:
    needs: build
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download qualityannotate
        uses: actions/download-artifact@v3
        with:
          name: qualityannotate
          path: ./build/qualityannotate-1.0.0-SNAPSHOT-runner
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open
      - name: Qualityannotate
        if: success() && steps.findPr.outputs.number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          GITHUB_PULL_REQUEST: ${{ steps.findPr.outputs.pr }}
          SONARQUBE_PROJECT: quyt_qualityannotate
          SONARQUBE_URL: https://sonarcloud.io/
          SONARQUBE_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONARQUBE_PULL_REQUEST: ${{ steps.findPr.outputs.pr }}
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "${PR_NUMBER}"
          ls
          ls build
          chmod +x ./build/qualityannotate-1.0.0-SNAPSHOT-runner
          mkdir -p config
          cp src/main/resources/application.yml config/
          ./build/qualityannotate-1.0.0-SNAPSHOT-runner
