---
name: release-build

on:  # yamllint disable-line rule:truthy
  release:
    types: [created]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build native executable
        run: "./gradlew -Pversion=\"${{ github.event.release.tag_name }}\" build -Dquarkus.package.type=native --no-daemon"
      - name: Upload native executable
        id: upload-native-executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/qualityannotate-${{ github.event.release.tag_name }}-runner
          asset_name: qualityannotate-${{ github.event.release.tag_name }}-linux
          asset_content_type: application/octet-stream
      - name: Upload config
        id: upload-config
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/resources/main/application.yml
          asset_name: application.yml
          asset_content_type: text/yaml
