---
name: release-build

on:  # yamllint disable-line rule:truthy
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'
      - name: Build native executable
        run: "./gradlew -Pversion=\"${{ github.event.release.tag_name }}\" build -Dquarkus.package.type=native"
      - name: Upload native executable
        id: upload-native-executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/qualityannotate-${{ github.event.release.tag_name }}-runner
          asset_name: qualityannotate-${{ github.event.release.tag_name }}-linux
          asset_content_type: application/octet-stream
      - name: Upload config
        id: upload-config
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/resources/main/application.yml
          asset_name: application.yml
          asset_content_type: text/yaml
